---
#- name: include role and loop with vars file
#  include_vars:
#    file: roles/osp-servers/vars/main.yml

- name: include role and loop with vars file
  include_tasks:
    file: servers.yml
  loop: "{{ osp_servers|dict2items }}"
  when: item.value != ""
